version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      # Discover and run linting in the 'src' directory
      - npm run lint

artifacts:
  files:
    - '**/*'
